### ISSUE TITLE
Authorized characters

### ISSUE THREAD

**Issue by MilleMiles** [blue-yonder/di-csv2xml#17]
Sometimes there is some spaces or others special characters in the first line of my files.
So, when I run di-csv2xml, the output file is not a valid XML file.

Are you able to preserve only authorized characters? Or replace all unauthorized characters by another?

**Comment by pacman82** [comment]
I am not sure if I get your usecase correctly. Yet from what I understand the Column names in your Headline can contain spaces and so on, which would the tool cause to render markups invalid markups such as `<A B>`. I fear any manipulation of the column names is out of scope for this tool. Please understand that `di-csv2xml` is not intended to be a general purpose CSV to XML converter, but is tailored to support Blue Yonder Customers in the creation of XML compatible with the *Blue Yonder: Supply and Demand API*. As such the columns of the customer supplied CSV already correspond to the names used in the Blue Yonder specific XML.
