### ISSUE TITLE
No silent operation, please remove the benchmark output

### ISSUE THREAD

**Issue by glitchtracker** [blue-yonder/di-csv2xml#43]
Hi,
that's great, but unfortunately it spits out "Processed 48 records in 1ms 606us 83ns", this is annoying.
Could you add an option to remove it ? Thanks

**Comment by pacman82** [comment]
`di-csv2xml 2.1.0` features a `--quite` flag

**Comment by glitchtracker** [comment]
oh, I didn't realize that you made a fix for that. Many thanks.
P.S : it's not on homebrew

**Comment by pacman82** [comment]
@stephan-hesselmann-by used to make the deployment to homebrew. I do not think he is with BY anymore.
