### ISSUE TITLE
di-csv2xml doesn't output blank values

### ISSUE THREAD

**Issue by glitchtracker** [blue-yonder/di-csv2xml#45]
Hi

I have this CSV
SKU;BRAND;NAME
S01;MyBRand1;MyName1
S02;;MayNAme2
S02;MyBRand2;MyName2

di-csv2xml will output

<?xml version="1.0" encoding="UTF-8"?>
<Category>
    <Record>
        <SKU>S01</SKU>
        <BRAND>MyBRand1</BRAND>
        <NAME>MyName1</NAME>
    </Record>
      <Record>
        <SKU>S02</SKU>
        <NAME>MyName2</NAME>
    </Record>
   <Record>
        <SKU>S03</SKU>
        <BRAND>MyBRand3</BRAND>
        <NAME>MyName3</NAME>
    </Record>
</Category>

This is a very big problem for me, I expected it would output 

<?xml version="1.0" encoding="UTF-8"?>
<Category>
    <Record>
        <SKU>S01</SKU>
        <BRAND>MyBRand1</BRAND>
        <NAME>MyName1</NAME>
    </Record>
      <Record>
        <SKU>S02</SKU>
        <BRAND>MyBRand1</BRAND>
        <NAME>MyName2</NAME>
    </Record>
   <Record>
        <SKU>S03</SKU>
        <BRAND>MyBRand3</BRAND>
        <NAME>MyName3</NAME>
    </Record>
</Category>

could you please make a flag to do this ?

Thanks

**Comment by pacman82** [comment]
Hello @glitchtracker ,

> This is a very big problem for me

I believe you, but `di-csv2xml` is not a generic csv to xml converter. It is specifically intended to generate XML for the Blue Yonder Supply and Demand API. Any usecase outside of that is considered out of scope.

However if this artefact is somewhat close to what you want to do feel free to fork it and adapt it to your needs.

Best, Markus

**Comment by glitchtracker** [comment]
understood, I found another more generic converter, csvprintf, since then
best regards

Le sam. 6 mai 2023 à 14:16, Markus Klein ***@***.***> a
écrit :
