### ISSUE TITLE
Maintainance

### ISSUE THREAD

**Issue by pacman82** [blue-yonder/di-csv2xml#46]
Hi @sebastian-neubauer-by ,

is there any interest from BY to maintain this. Or should I mark it in the readme that this artefact is sunset?

Best, Markus

**Comment by philippmack** [comment]
Hi Markus,
I'm still using it frequently at BY and I would take over ownership.
Best
Philipp Mack

**Comment by pacman82** [comment]
Thanks @philippmack ,

happy to help out once in a while.

Cheers, Markus

**Comment by sebastianneubauer** [comment]
We would also move this repo to the new BY OSS org as it seems it is still useful and used. Fine?

**Comment by pacman82** [comment]
Fine with me ;-)
